export type RestaurantCategory =
  | "ITALIAN" | "MEXICAN" | "CHINESE" | "JAPANESE" | "AMERICAN"
  | "INDIAN" | "THAI" | "MEDITERRANEAN" | "FAST_FOOD" | "SEAFOOD"
  | "STEAKHOUSE" | "VEGETARIAN" | "VEGAN" | "BAKERY" | "CAFE"
  | "BAR" | "PUB" | "FINE_DINING" | "CASUAL_DINING" | "FOOD_TRUCK"
  | "OTHER";